### ISSUE TITLE
Is elgg_slider compatible with Elgg 2.3 ?  It works well on 1.11 but after reinstall to 2.3 I receive error.

### ISSUE THREAD

**Issue by VladVuk** [hypeJunction/elgg_slider#1]
**ERROR MESSAGE WHEN TRY TO OPEN THE FRONT PAGE ([http://213.136.90.112/](http://213.136.90.112/)) :**
Argument 2 passed to Elgg\ViewsService::renderView() must be of the type array, string given, called in /var/www/html/ar/vendor/elgg/elgg/engine/lib/views.php on line 337

TypeError Object
(
[message:protected] => Argument 2 passed to Elgg\ViewsService::renderView() must be of the type array, string given, called in /var/www/html/ar/vendor/elgg/elgg/engine/lib/views.php on line 337
[string:Error:private] => TypeError: Argument 2 passed to Elgg\ViewsService::renderView() must be of the type array, string given, called in /var/www/html/ar/vendor/elgg/elgg/engine/lib/views.php on line 337 and defined in /var/www/html/ar/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php:264
Stack trace:
#0 /var/www/html/ar/vendor/elgg/elgg/engine/lib/views.php(337): Elgg\ViewsService->renderView('page/components...', 'slides', false, '')
#1 /var/www/html/ar/mod/helena/views/default/page/elements/featured.php(51): elgg_view('page/components...', 'slides')
#2 /var/www/html/ar/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php(370): include('/var/www/html/a...')
#3 /var/www/html/ar/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php(306): Elgg\ViewsService->renderViewFile('page/elements/f...', Array, 'default', true)
#4 /var/www/html/ar/vendor/elgg/elgg/engine/lib/views.php(337): Elgg\ViewsService->renderView('page/elements/f...', Array, false, 'default')
#5 /var/www/html/ar/mod/helena/views/default/page/layouts/helena_front_page.php(10): elgg_view('page/elements/f...')
#6 /var/www/html/ar/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php(370): include('/var/www/html/a...')
#7 /var/www/html/ar/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php(306): Elgg\ViewsService->renderViewFile('page/layouts/he...', Array, 'default', true)
#8 /var/www/html/ar/vendor/elgg/elgg/engine/lib/views.php(337): Elgg\ViewsService->renderView('page/layouts/he...', Array, false, 'default')
#9 /var/www/html/ar/vendor/elgg/elgg/engine/lib/views.php(709): elgg_view('page/layouts/he...', Array)
#10 /var/www/html/ar/mod/helena/views/default/resources/index.php(17): elgg_view_layout('helena_front_pa...', NULL)
#11 /var/www/html/ar/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php(370): include('/var/www/html/a...')
#12 /var/www/html/ar/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php(306): Elgg\ViewsService->renderViewFile('resources/index', Array, 'default', true)
#13 /var/www/html/ar/vendor/elgg/elgg/engine/lib/views.php(514): Elgg\ViewsService->renderView('resources/index', Array)
#14 /var/www/html/ar/vendor/elgg/elgg/engine/lib/pagehandler.php(250): elgg_view_resource('index')
#15 [internal function]: elgg_front_page_handler(Array, '')
#16 /var/www/html/ar/vendor/elgg/elgg/engine/classes/Elgg/Router.php(100): call_user_func('elgg_front_page...', Array, '')
#17 /var/www/html/ar/vendor/elgg/elgg/engine/classes/Elgg/Application.php(436): Elgg\Router->route(Object(Elgg\Http\Request))
#18 /var/www/html/ar/vendor/elgg/elgg/engine/classes/Elgg/Application.php(384): Elgg\Application->run()
#19 /var/www/html/ar/index.php(8): Elgg\Application::index()
#20 {main}
[code:protected] => 0
[file:protected] => /var/www/html/ar/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php
[line:protected] => 264
[trace:Error:private] => Array
(
[0] => Array
(
[file] => /var/www/html/ar/vendor/elgg/elgg/engine/lib/views.php
[line] => 337
[function] => renderView
[class] => Elgg\ViewsService
[type] => ->
[args] => Array
(
[0] => page/components/slider
[1] => slides
[2] => 
[3] => 
)

)

[1] => Array
(
[file] => /var/www/html/ar/mod/helena/views/default/page/elements/featured.php
[line] => 51
[function] => elgg_view
[args] => Array
(
[0] => page/components/slider
[1] => slides
)

)

[2] => Array
(
[file] => /var/www/html/ar/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php
[line] => 370
[args] => Array
(
[0] => /var/www/html/ar/mod/helena/views/default/page/elements/featured.php
)

[function] => include
)

[3] => Array
(
[file] => /var/www/html/ar/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php
[line] => 306
[function] => renderViewFile
[class] => Elgg\ViewsService
[type] => ->
[args] => Array
(
[0] => page/elements/featured
[1] => Array
(
)

[2] => default
[3] => 1
)

)

[4] => Array
(
[file] => /var/www/html/ar/vendor/elgg/elgg/engine/lib/views.php
[line] => 337
[function] => renderView
[class] => Elgg\ViewsService
[type] => ->
[args] => Array
(
[0] => page/elements/featured
[1] => Array
(
)

[2] => 
[3] => default
)

)

[5] => Array
(
[file] => /var/www/html/ar/mod/helena/views/default/page/layouts/helena_front_page.php
[line] => 10
[function] => elgg_view
[args] => Array
(
[0] => page/elements/featured
)

)

[6] => Array
(
[file] => /var/www/html/ar/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php
[line] => 370
[args] => Array
(
[0] => /var/www/html/ar/mod/helena/views/default/page/layouts/helena_front_page.php
)

[function] => include
)

[7] => Array
(
[file] => /var/www/html/ar/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php
[line] => 306
[function] => renderViewFile
[class] => Elgg\ViewsService
[type] => ->
[args] => Array
(
[0] => page/layouts/helena_front_page
[1] => Array
(
[layout] => helena_front_page
)

[2] => default
[3] => 1
)

)

[8] => Array
(
[file] => /var/www/html/ar/vendor/elgg/elgg/engine/lib/views.php
[line] => 337
[function] => renderView
[class] => Elgg\ViewsService
[type] => ->
[args] => Array
(
[0] => page/layouts/helena_front_page
[1] => Array
(
[layout] => helena_front_page
)

[2] => 
[3] => default
)

)

[9] => Array
(
[file] => /var/www/html/ar/vendor/elgg/elgg/engine/lib/views.php
[line] => 709
[function] => elgg_view
[args] => Array
(
[0] => page/layouts/helena_front_page
[1] => Array
(
[layout] => helena_front_page
)

)

)

[10] => Array
(
[file] => /var/www/html/ar/mod/helena/views/default/resources/index.php
[line] => 17
[function] => elgg_view_layout
[args] => Array
(
[0] => helena_front_page
[1] => 
)

)

[11] => Array
(
[file] => /var/www/html/ar/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php
[line] => 370
[args] => Array
(
[0] => /var/www/html/ar/mod/helena/views/default/resources/index.php
)

[function] => include
)

[12] => Array
(
[file] => /var/www/html/ar/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php
[line] => 306
[function] => renderViewFile
[class] => Elgg\ViewsService
[type] => ->
[args] => Array
(
[0] => resources/index
[1] => Array
(
)

[2] => default
[3] => 1
)

)

[13] => Array
(
[file] => /var/www/html/ar/vendor/elgg/elgg/engine/lib/views.php
[line] => 514
[function] => renderView
[class] => Elgg\ViewsService
[type] => ->
[args] => Array
(
[0] => resources/index
[1] => Array
(
)

)

)

[14] => Array
(
[file] => /var/www/html/ar/vendor/elgg/elgg/engine/lib/pagehandler.php
[line] => 250
[function] => elgg_view_resource
[args] => Array
(
[0] => index
)

)

[15] => Array
(
[function] => elgg_front_page_handler
[args] => Array
(
[0] => Array
(
)

[1] => 
)

)

[16] => Array
(
[file] => /var/www/html/ar/vendor/elgg/elgg/engine/classes/Elgg/Router.php
[line] => 100
[function] => call_user_func
[args] => Array
(
[0] => elgg_front_page_handler
[1] => Array
(
)

[2] => 
)

)

[17] => Array
(
[file] => /var/www/html/ar/vendor/elgg/elgg/engine/classes/Elgg/Application.php
[line] => 436
[function] => route
[class] => Elgg\Router
[type] => ->
[args] => Array
(
[0] => Elgg\Http\Request Object
(
[attributes] => Symfony\Component\HttpFoundation\ParameterBag Object
(
[parameters:protected] => Array
(
)

)

[request] => Symfony\Component\HttpFoundation\ParameterBag Object
(
[parameters:protected] => Array
(
)

)

[query] => Symfony\Component\HttpFoundation\ParameterBag Object
(
[parameters:protected] => Array
(
[__elgg_uri] => /
)

)

[server] => Symfony\Component\HttpFoundation\ServerBag Object
(
[parameters:protected] => Array
(
[USER] => apache
[HOME] => /usr/share/httpd
[SCRIPT_NAME] => /index.php
[REQUEST_URI] => /
[QUERY_STRING] => 
[REQUEST_METHOD] => GET
[SERVER_PROTOCOL] => HTTP/1.1
[GATEWAY_INTERFACE] => CGI/1.1
[REMOTE_PORT] => 62394
[SCRIPT_FILENAME] => /var/www/html/ar/index.php
[SERVER_ADMIN] => webmaster@almanacar.com
[CONTEXT_DOCUMENT_ROOT] => /var/www/html/ar/
[CONTEXT_PREFIX] => 
[REQUEST_SCHEME] => http
[DOCUMENT_ROOT] => /var/www/html/ar/
[REMOTE_ADDR] => 85.114.42.205
[SERVER_PORT] => 80
[SERVER_ADDR] => 213.136.90.112
[SERVER_NAME] => 213.136.90.112
[SERVER_SOFTWARE] => Apache/2.4.6 (CentOS) PHP/5.4.16
[SERVER_SIGNATURE] => 
[PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
[HTTP_COOKIE] => elggperm=zmkeIQdCSG2Z3f5i5OvPHF7e13UBLof3; Elgg=n7khbp1k3cv3vq3kllj81jd1j9
[HTTP_ACCEPT_LANGUAGE] => en-US,en;q=0.8,hr;q=0.6
[HTTP_ACCEPT_ENCODING] => gzip, deflate, sdch
[HTTP_REFERER] => http://213.136.90.112/admin/plugins
[HTTP_DNT] => 1
[HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
[HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
[HTTP_UPGRADE_INSECURE_REQUESTS] => 1
[HTTP_CONNECTION] => keep-alive
[HTTP_HOST] => 213.136.90.112
[proxy-nokeepalive] => 1
[UNIQUE_ID] => WHyyXZG3qv3pAi8rQI6EVQAAAAA
[FCGI_ROLE] => RESPONDER
[PHP_SELF] => /index.php
[REQUEST_TIME_FLOAT] => 1484567133.1749
[REQUEST_TIME] => 1484567133
)

)

[files] => Symfony\Component\HttpFoundation\FileBag Object
(
[parameters:protected] => Array
(
)

)

[cookies] => Symfony\Component\HttpFoundation\ParameterBag Object
(
[parameters:protected] => Array
(
[elggperm] => zmkeIQdCSG2Z3f5i5OvPHF7e13UBLof3
[Elgg] => n7khbp1k3cv3vq3kllj81jd1j9
)

)

[headers] => Symfony\Component\HttpFoundation\HeaderBag Object
(
[headers:protected] => Array
(
[cookie] => Array
(
[0] => elggperm=zmkeIQdCSG2Z3f5i5OvPHF7e13UBLof3; Elgg=n7khbp1k3cv3vq3kllj81jd1j9
)

[accept-language] => Array
(
[0] => en-US,en;q=0.8,hr;q=0.6
)

[accept-encoding] => Array
(
[0] => gzip, deflate, sdch
)

[referer] => Array
(
[0] => http://213.136.90.112/admin/plugins
)

[dnt] => Array
(
[0] => 1
)

[accept] => Array
(
[0] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
)

[user-agent] => Array
(
[0] => Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
)

[upgrade-insecure-requests] => Array
(
[0] => 1
)

[connection] => Array
(
[0] => keep-alive
)

[host] => Array
(
[0] => 213.136.90.112
)

)

[cacheControl:protected] => Array
(
)

)

[content:protected] => 
[languages:protected] => 
[charsets:protected] => 
[encodings:protected] => 
[acceptableContentTypes:protected] => 
[pathInfo:protected] => 
[requestUri:protected] => /
[baseUrl:protected] => 
[basePath:protected] => 
[method:protected] => 
[format:protected] => 
[session:protected] => 
[locale:protected] => 
[defaultLocale:protected] => en
)

)

)

[18] => Array
(
[file] => /var/www/html/ar/vendor/elgg/elgg/engine/classes/Elgg/Application.php
[line] => 384
[function] => run
[class] => Elgg\Application
[type] => ->
[args] => Array
(
)

)

[19] => Array
(
[file] => /var/www/html/ar/index.php
[line] => 8
[function] => index
[class] => Elgg\Application
[type] => ::
[args] => Array
(
)

)

)

[previous:Error:private] => 
)

-------------------------------------------------------------------------------------------

**THE SOURCE CODE IN WHICH I CALL ELGG_SLIDER AND THE ERROR IN LINE (16.):**
<?php

 
$plugin = elgg_get_plugin_from_id('helena');

// Get the newest image
$img = get_front_page_image($params['entity']);

if (!$img) { 
	$img_src = elgg_get_site_url() . "mod/helena/graphics/images/featured.jpg";
} else {	
	$img_src = $img->getIconURL('large');
	$img_src = elgg_format_url($img_src);
}

**echo elgg_view('page/components/slider', 'slides');**
elgg_require_js("page/components/slider");

$img_1 = elgg_get_site_url() . "mod/helena/graphics/intro_slide_01a.jpg";
$img_2 = elgg_get_site_url() . "mod/helena/graphics/intro_slide_01b.jpg";
$img_3 = elgg_get_site_url() . "mod/helena/graphics/intro_slide_04a.jpg";
$img_4 = elgg_get_site_url() . "mod/helena/graphics/intro_slide_04b.jpg";
$img_5 = elgg_get_site_url() . "mod/helena/graphics/intro_slide_05a.jpg";
$img_6 = elgg_get_site_url() . "mod/helena/graphics/intro_slide_05b.jpg";
$img_7 = elgg_get_site_url() . "mod/helena/graphics/intro_slide_02a.jpg";
$img_8 = elgg_get_site_url() . "mod/helena/graphics/intro_slide_02b.jpg";
$img_9 = elgg_get_site_url() . "mod/helena/graphics/intro_slide_06a.jpg";
$img_10 = elgg_get_site_url() . "mod/helena/graphics/intro_slide_06b.jpg";
?>

<div class="elgg-featured-container" style="background-color:#f6f6f6;">
	<div class="elgg-featured">
		<div class="featured-image" style="max-width:1260px; margin: 0 auto;  display:none;">

			<div  class="elgg-slick-slider" data-slick='{"infinite": true, "fade": true, "autoplay": true,  "autoplaySpeed": 3000, "speed": 2000, "pauseOnHover": false, "slidesToShow": 1, "slidesToScroll": 1, "dots": false, "onBeforeChange" : "beforeChange", "onAfterChange":  "afterChange", "draggable" : false, "arrows": false }' >
				<div class="elgg-slick-slide"> <img src="<?php echo $img_1;?>"> </div>
				<div class="elgg-slick-slide"> <img src="<?php echo $img_2;?>"> </div>
				<div class="elgg-slick-slide"> <img src="<?php echo $img_3;?>"> </div>
				<div class="elgg-slick-slide"> <img src="<?php echo $img_4;?>"> </div>
				<div class="elgg-slick-slide"> <img src="<?php echo $img_5;?>"> </div>
				<div class="elgg-slick-slide"> <img src="<?php echo $img_6;?>"> </div>
				<div class="elgg-slick-slide"> <img src="<?php echo $img_7;?>"> </div>
				<div class="elgg-slick-slide"> <img src="<?php echo $img_8;?>"> </div>
				<div class="elgg-slick-slide"> <img src="<?php echo $img_9;?>"> </div>
				<div class="elgg-slick-slide"> <img src="<?php echo $img_10;?>"> </div>
			</div>
		</div>
	</div>
</div>

<script type='text/javascript'>
$(window).load(function(){
    $('.featured-image').show();
});
</script>

**Comment by hypeJunction** [comment]
``echo elgg_view('page/components/slider', 'slides');`` second attribute must be an array.
Why bother with this plugin if you are rendering the views yourself?
